import pytumblr
import json
import random
import time

# Authenticate via OAuth
client = pytumblr.TumblrRestClient(
  ‘<consumer_key>’,
  ‘<consumer_secret>’,
  ‘<oauth_token>’,
  ‘<oauth_secret>’,
)

def getVerb():
	verbs = [
		"adopt",
		"affirm",
		"afford",
		"agree",
		"ail",
		"alert",
		"allege",
		"allow",
		"allude",
		"absorb",
		"accept",
		"acknowledge",
		"admire",
		"adore",
		"advise",
		"afford",
		"age",
		"agree",
		"appreciate",
		"arrange",
		"assure",
		"astonish",
		"attract",
		"attribute",
		"awaken",
		"balance",
		"bask",
		"battle",
		"be",
		"beautify",
		"beguile",
		"behold",
		"believe",
		"bewitch",
		"blister",
		"blossom",
		"blush",
		"break",
		"breath",
		"brighten",
		"bring",
		"build",
		"bury",
		"buy",
		"captivate",
		"care",
		"caress",
		"carry",
		"catch",
		"celebrate",
		"challenge",
		"chaperone",
		"charm",
		"cheer",
		"cherish",
		"choose",
		"clean",
		"cleanse",
		"click",
		"coach",
		"coax",
		"color",
		"combat",
		"come",
		"comfort",
		"commemorate",
		"communicate",
		"compare",
		"complement",
		"complete",
		"confide",
		"connect",
		"consider",
		"console",
		"contemplate",
		"continue",
		"control",
		"convey",
		"counsel",
		"count",
		"covet",
		"crack",
		"crave",
		"crawl",
		"crinkle",
		"cruise",
		"crush",
		"cry",
		"cuddle",
		"damage",
		"dare",
		"daze",
		"dazzle",
		"decorate",
		"defeat",
		"delight",
		"demonstrate",
		"depart",
		"depend",
		"desire",
		"devote",
		"die",
		"dimple",
		"discharge",
		"discipline",
		"display",
		"dote",
		"draw",
		"dream",
		"drink",
		"drive",
		"dwell",
		"ease",
		"educate",
		"embattle",
		"embellish",
		"enchant",
		"encourage",
		"engineer",
		"enhance",
		"enjoy",
		"entertain",
		"enthrall",
		"entomb",
		"entrance",
		"entrap",
		"entrust",
		"esteem",
		"exalt",
		"excel",
		"excite",
		"experience",
		"explain",
		"explore",
		"express",
		"extend",
		"extol",
		"eye",
		"fall",
		"fancy",
		"fantasize",
		"fascinate",
		"feed",
		"feel",
		"fight",
		"fill",
		"find",
		"flake",
		"flare",
		"flatter",
		"flirt",
		"flush",
		"fly",
		"forgive",
		"freckle",
		"free",
		"freshen",
		"fulfill",
		"furnish",
		"furrow",
		"gather",
		"gawk",
		"gaze",
		"get",
		"give",
		"glance",
		"glorify",
		"glow",
		"go",
		"grab",
		"grade",
		"graduate",
		"greet",
		"grieve",
		"grill",
		"grow",
		"guide",
		"habituate",
		"hail",
		"handle",
		"hang",
		"have",
		"heal",
		"help",
		"hold",
		"honor",
		"hook",
		"hope",
		"host",
		"house",
		"hug",
		"hunger",
		"hurt",
		"hypnotize",
		"idealize",
		"idolize",
		"impart",
		"infatuate",
		"influence",
		"inhabit",
		"inspire",
		"instill",
		"instruct",
		"intrigue",
		"invest",
		"invite",
		"irritate",
		"join",
		"kiss",
		"knock",
		"know",
		"lament",
		"laugh",
		"lead",
		"lean",
		"learn",
		"like",
		"listen",
		"live",
		"long",
		"look",
		"lose",
		"love",
		"lure",
		"lust",
		"luxuriate",
		"make",
		"march",
		"marry",
		"massage",
		"mate",
		"mature",
		"maximize",
		"meet",
		"memorialize",
		"mesmerize",
		"miss",
		"mottle",
		"mourn",
		"move",
		"nod",
		"nurture",
		"obey",
		"observe",
		"obsess",
		"occupy",
		"offer",
		"ogle",
		"organize",
		"outgrew",
		"owe",
		"own",
		"pain",
		"paint",
		"pair",
		"pamper",
		"participate",
		"pass",
		"peel",
		"perform",
		"perish",
		"persevere",
		"perspire",
		"persuade",
		"picnic",
		"pilot",
		"pine",
		"plan",
		"play",
		"please",
		"pleasure",
		"pour",
		"praise",
		"pray",
		"prepare",
		"prize",
		"proclaim",
		"promise",
		"prosper",
		"protect",
		"provide",
		"purchase",
		"radiate",
		"recall",
		"reciprocate",
		"recognize",
		"reflect",
		"regard",
		"reinforce",
		"rejoice",
		"relate",
		"relax",
		"relish",
		"relocate",
		"rely",
		"remember",
		"remodel",
		"renovate",
		"reside",
		"respect",
		"rest",
		"revere",
		"ride",
		"romance",
		"rub",
		"sacrifice",
		"safeguard",
		"salute",
		"satisfy",
		"savor",
		"scab",
		"scar",
		"school",
		"seduce",
		"serve",
		"set",
		"settle",
		"share",
		"shave",
		"shield",
		"shift",
		"shine",
		"show",
		"shower",
		"shrivel",
		"sign",
		"smear",
		"smooch",
		"smudge",
		"snuggle",
		"speed",
		"spend",
		"spoon",
		"stain",
		"stare",
		"steer",
		"stick",
		"stop",
		"strike",
		"strive",
		"stroke",
		"study",
		"succumb",
		"suck",
		"suffer",
		"sunbathe",
		"supervise",
		"support",
		"surprise",
		"sweat",
		"sweep",
		"swell",
		"swoon",
		"symbolize",
		"take",
		"talk",
		"tan",
		"tarnish",
		"teach",
		"tell",
		"tempt",
		"test",
		"thank",
		"think",
		"tingle",
		"tint",
		"toast",
		"tone",
		"touch",
		"tour",
		"transition",
		"transport",
		"treasure",
		"triple",
		"trust",
		"turn",
		"tutor",
		"understand",
		"unfurl",
		"unite",
		"unpack",
		"value",
		"venerate",
		"view",
		"visit",
		"voice",
		"walk",
		"want",
		"wash",
		"weather",
		"wed",
		"weep",
		"welcome",
		"win",
		"wine",
		"wish",
		"witness",
		"work",
		"worship",
		"wow",
		"wrinkle",
		"yearn",
		"zoom"
	]

	return random.choice(verbs)

def getNoun():
	nouns = [
		"youtube",
		"mother",
		"ass",
		"piano",
		"dance",
		"murder",
		"mcrib sandwich",
		"sausage",
		"taco bell",
		"enema",
		"erectile dysfunction",
		"ducks",
		"egg rolls",
		"underwear",
		"penguins",
		"Benedict Cumberbatch",
		"elf",
		"positive feedback"
		"day before",
		"elegant question",
		"mermaid egg",
		"mad cow disease",
		"nine states",
		"observation tower",
		"mental disorder",
		"kind and gentle folk",
		"boiling water",
		"drug addict",
		"idea he suggested",
		"party of the first part",
		"towelette",
		"most beautiful girl",
		"shivering toes",
		"wiley coyote",
		"legal warrant",
		"sheep dip",
		"planetary house",
		"multi-billionaire",
		"indestructible empire",
		"wiener",
		"sealed off tomb",
		"deer antler",
		"pervert",
		"pile of decomposition",
		"self-sacrifice",
		"dentists drill",
		"famous landscape painting",
		"antidepressant drug",
		"brainchild",
		"video game",
		"double fault",
		"toilet",
		"rough-skinned newt",
		"wrinkle",
		"pillow",
		"natural history",
		"animal psychology department",
		"internal respiration",
		"Erie Canal",
		"lips",
		"stock car",
		"willow",
		"unemployed people",
		"bouncy ball",
		"eskimo",
		"stick figure",
		"junkies",
		"descending color",
		"pancake",
		"indirect expression",
		"fluffy clouds",
		"new version",
		"extremity",
		"friendly claim",
		"modern times",
		"lettuce",
		"skull and crossbones",
		"weed wacker",
		"diplomatic negotiation",
		"police department",
		"mistress",
		"light bulb",
		"manipulating ass",
		"bored child",
		"life raft",
		"trust fund",
		"space emulator",
		"chicken stew",
		"mental case",
		"fact that I dont think",
		"sight of the girl",
		"national security agency",
		"knights service",
		"winners",
		"manure",
		"microwaved eggs",
		"nudist camp",
		"merry bells",
		"idiot",
		"musical chairs",
		"informal request",
		"mathematics department",
		"hiking boots",
		"dirty coffee cup",
		"international law enforcement agency",
		"preventive strike",
		"obviousness",
		"nature trail",
		"sound barrier",
		"jungle psychology",
		"elastic band",
		"licensed rat breeder",
		"police squad",
		"big polar bear",
		"messiness",
		"sneaky criminal",
		"litter pan",
		"remnant of chaos",
		"reading party",
		"monkey",
		"obsessive-compulsive disorder",
		"people",
		"roadblock",
		"greater central area",
		"old irish cottage",
		"legal document",
		"totempole",
		"lieutenant governor",
		"sewing-machine operator",
		"baby",
		"main people",
		"pocket flask",
		"pilot chart",
		"corn cake",
		"mad-dog skullcap",
		"patrolman",
		"control account",
		"karate",
		"unit of unholy depth",
		"volcanic crater",
		"hunting ground",
		"dragon",
		"big jerk",
		"really tough guy",
		"friendly grandma",
		"refrigerator",
		"generalized bond",
		"striped hyena",
		"mediation",
		"breakfast table",
		"strep throat",
		"telephone",
		"locker room",
		"tomato concentrate",
		"biology lab",
		"radio beam",
		"convection oven",
		"orbital plane",
		"dog poop",
		"twinkling uncleanness",
		"trooper",
		"suckling pig",
		"love of her life",
		"coffee pot",
		"amish folk",
		"sweet tailpipe",
		"divergent thinking",
		"private investor",
		"polkdot",
		"nonbeliever",
		"electric furnace",
		"abnormal behavior",
		"haunted graveyard",
		"change for good",
		"dingle berry",
		"pistol",
		"nibblets",
		"phonograph record",
		"railroad worm",
		"kite",
		"president of the night",
		"fluffy slippers",
		"internal control",
		"keepsake machete",
		"jellybean",
		"snowshoe hare",
		"crazy grandma",
		"matrimonial law",
		"ways of world",
		"laser beams",
		"wild, wild sheep",
		"gaming laptop",
		"sideboard",
		"whole blood",
		"kitty cat",
		"clan member",
		"jet ski",
		"latest version",
		"candlestick maker",
		"baptist church",
		"kitty",
		"useless brakes",
		"negative mood",
		"place of business",
		"constant reminder",
		"tentacle",
		"general knowledge",
		"travel guidebook",
		"toast",
		"french chef",
		"tank",
		"thunder legs",
		"scourge upon the earth",
		"sphere of influence",
		"serious question",
		"first born",
		"indiscriminate killer",
		"personal credit line",
		"hairy legs",
		"ice cream",
		"crime scene",
		"rocket science",
		"latest job",
		"date of improvement",
		"invisibility cloak",
		"people who are hurt",
		"ships captain",
		"snake",
		"background story",
		"mimicker",
		"gothic romance",
		"liquid oxygen",
		"snakehead",
		"notion of love",
		"fairy lantern",
		"conjugal visitation",
		"large chested population",
		"anticipated front",
		"tire iron",
		"skinny woman",
		"linoleum cutter",
		"circle of life",
		"shotgun",
		"cupcake",
		"Chief Justice",
		"baked bread",
		"natural childbirth",
		"arrogant hitman",
		"broken promises",
		"dominator",
		"money bags",
		"overlord",
		"investment advisor",
		"meeting with my mom",
		"confusing situation",
		"overstuffed chair",
		"state line",
		"regional atomic mass",
		"sentry box",
		"crowd pleaser",
		"promotion system",
		"quiet man",
		"exorcism",
		"love grass",
		"storage battery",
		"fighting people",
		"dog sled",
		"platinum blonde",
		"department of justice",
		"manic",
		"upholstery",
		"halfbreed Apache",
		"abusive husband",
		"strawberry daiquiri",
		"false partnership",
		"cavity search",
		"six-gilled shark",
		"kind words",
		"city boy",
		"cave man",
		"milk",
		"bad tempered troll",
		"puppy",
		"scum bag",
		"peg leg",
		"baseball fans",
		"rate of exchange cactus",
		"locomotive",
		"coffee table",
		"everyone including mom",
		"people that dont like you",
		"update",
		"sock gnomes",
		"wish bone",
		"generalized seizure",
		"suitcase",
		"burglar alarm",
		"lemon lily",
		"moral philosophy",
		"ocean state",
		"mortician",
		"hellfire raiser",
		"bountiful harvest",
		"people I dont love",
		"blink of an eye",
		"suit of armor",
		"quantum leap",
		"nunchucks",
		"people I know",
		"solar sound barrier",
		"governing body",
		"captain fantastic",
		"chief constable",
		"town drunk",
		"vehicular traffic",
		"dinnertime",
		"pole dancer",
		"kentucky fried chicken",
		"only thing",
		"rat kangaroo",
		"laser beam",
		"solar furnace",
		"pizza",
		"saddle horse",
		"play tapy",
		"pink toenails",
		"carousing drunk",
		"first concern",
		"preacher",
		"eternal afterlife",
		"ninja",
		"prickly-seeded spinach",
		"sock puppet",
		"festival of lights",
		"private investigator",
		"fools knowledge",
		"self-taught art",
		"pot smoker",
		"grandmas house",
		"olfactory bulb",
		"short-haired idiot",
		"one thought",
		"friendly comment",
		"vanquis of everything",
		"praying mantis",
		"firehouse",
		"last known location",
		"scientific method",
		"zombies",
		"pudding stone protector",
		"caution sign",
		"lynch law",
		"bird brain",
		"turkey",
		"raspberry bush",
		"little tattletale",
		"trampoline",
		"rain",
		"normal distribution",
		"upset stomach",
		"slacker",
		"imbecile",
		"aggressive criminal",
		"young fellow",
		"gym rat",
		"twisted madmen",
		"space invader",
		"yogurt",
		"science and technology",
		"painting",
		"veggieland",
		"battle",
		"ways of the world",
		"applesauce",
		"last years jailbreak",
		"small children",
		"grandmas business",
		"onionskin",
		"rainbow flag",
		"law enforcer",
		"prostitute",
		"wiley madman",
		"physics lab",
		"muddy boots",
		"belly dancer",
		"American Indian",
		"sledding people",
		"tense system",
		"some buttered toast",
		"fertility clinic",
		"tractor",
		"strife",
		"article of clothing",
		"tract of arms",
		"bargain breaker",
		"bounty hunter",
		"decoy",
		"good book",
		"squirting cucumber",
		"secondhand smoke",
		"whip",
		"important plan",
		"patrol",
		"unicorn",
		"presidency",
		"sheered sheep",
		"character witness",
		"stolen property",
		"spiral cake",
		"potato",
		"salad sanatorium",
		"dust bunny",
		"bathroom",
		"poop",
		"presbyterian church",
		"cats ear",
		"chemical weapons",
		"pervasiveness",
		"wet suit",
		"wedge bone",
		"fact of life",
		"alien invasion",
		"thingumajig"
	]

	return random.choice(nouns)

def getAdj():
	adj = [
		"hot",
		"dry",
		"even",
		"fat",
		"icy",
		"neat",
		"wet",
		"bald",
		"bushy",
		"cold",
		"cool",
		"damp",
		"dusty",
		"firm",
		"flat",
		"fuzzy",
		"hard",
		"itchy",
		"limp",
		"lumpy",
		"mushy",
		"oily",
		"pulpy",
		"soft",
		"thin",
		"warm",
		"wavy",
		"wide",
		"wiry",
		"ample",
		"blunt",
		"bulky",
		"bumpy",
		"caked",
		"clean",
		"dense",
		"dirty",
		"downy",
		"filmy",
		"furry",
		"gooey",
		"grimy",
		"grubby",
		"hairy",
		"harsh",
		"jagged",
		"level",
		"lined",
		"loose",
		"moist",
		"rigid",
		"rough",
		"rusty",
		"rutted",
		"sandy",
		"sheer",
		"silky",
		"slick",
		"slimy",
		"soapy",
		"soggy",
		"solid",
		"spiky",
		"spiny",
		"stiff",
		"syrupy",
		"thick",
		"tiled",
		"tough",
		"tweedy",
		"woven",
		"zigzag",
		"angular",
		"barbed",
		"broken",
		"bubbly",
		"carved",
		"chunky",
		"clammy",
		"coarse",
		"dented",
		"doughy",
		"etched",
		"fleecy",
		"flimsy",
		"fluffy",
		"fluted",
		"frigid",
		"frothy",
		"glassy",
		"glazed",
		"glossy",
		"grainy",
		"greasy",
		"gritty",
		"hollow",
		"inlaid",
		"ironed",
		"knitted",
		"mosaic",
		"narrow",
		"padded",
		"pointy",
		"ragged",
		"ribbed",
		"ridged",
		"scored",
		"shaggy",
		"smooth",
		"soaked",
		"sodden",
		"soiled",
		"spongy",
		"steely",
		"sticky",
		"sweaty",
		"thorny",
		"uneven",
		"viscous",
		"bloated",
		"bristly",
		"bulging",
		"chafing",
		"chapped",
		"damaged",
		"fragile",
		"gnarled",
		"grating",
		"grooved",
		"layered",
		"pleated",
		"pliable",
		"pointed",
		"prickly",
		"printed",
		"rasping",
		"refined",
		"rubbery",
		"scarred",
		"scraped",
		"sopping",
		"springy",
		"stubbly",
		"swollen",
		"velvety",
		"woollen",
		"wrinkled",
		"yielding",
		"abrasive",
		"bendable",
		"circular",
		"cratered",
		"cushioned",
		"drenched",
		"embossed",
		"engorged",
		"engraved",
		"feathery",
		"freezing",
		"gossamer",
		"granular",
		"gravelly",
		"indented",
		"inflated",
		"leathery",
		"metallic",
		"polished",
		"scalding",
		"serrated",
		"slippery",
		"stuccoed",
		"veneered",
		"withered",
		"blemished",
		"blistered",
		"crocheted",
		"distended",
		"distorted",
		"enamelled",
		"encrusted",
		"glutinous",
		"imprinted",
		"inscribed",
		"irregular",
		"luke-warm",
		"malleable",
		"ornamented",
		"patterned",
		"pot-holed",
		"saturated",
		"scratched",
		"throbbing",
		"unyielding",
		"varnished",
		"vibrating",
		"corrugated",
		"crenelated",
		"dehydrated",
		"gelatinous",
		"pockmarked",
		"sculptured",
		"long-haired",
		"razor-sharp",
		"sharp-edged",
		"unblemished",
		"unbreakable",
		"waterlogged",
		"impenetrable",
		"uncomfortable",
		"adulterous",
		"alcoholic",
		"angry",
		"arrogant",
		"at-the-ready",
		"bat-shit-crazy",
		"blathering",
		"bull headed",
		"confused",
		"cruel-hearted",
		"demanding",
		"drunken",
		"fiercely-loyal",
		"flickering",
		"flirting",
		"free-loading",
		"frisky",
		"greedy",
		"hateful",
		"house-broken",
		"hyperactive",
		"high-end",
		"idiotic",
		"infuriating",
		"insecure",
		"maniacal",
		"mentally impaired",
		"misunderstood",
		"naked",
		"narrow-minded",
		"out-of-control",
		"outnumbered",
		"pea-brained",
		"rebellious",
		"self-absorbed",
		"shaky",
		"shivering",
		"sickened",
		"slippery",
		"stubborn",
		"territorial",
		"tripping",
		"twisted",
		"underhanded",
		"useless",
		"vengeful",
		"vile",
		"yapping",
		"zippy",
		"zombie like"
	]

	return random.choice(adj)

def getPost():
	sentence = random.randrange(0,16) #an integer >= a and < b
	sent = ""

	if sentence == 0:
		sent = "why do " + getNoun() + " are so " + getAdj()
	if sentence == 1:
		sent = "okay but can we talk about " + getNoun()
	if sentence == 2:
		sent = "what she says: \"" + getAdj() + "\" <br> what she means: \"" + getAdj() + "\""
	if sentence == 3:
		sent = "okay but imagine " + getVerb() + " and " + getVerb() + " at the same time"
	if sentence == 4:
		sent = "im the type of person who " + getVerb() + "s with " + getNoun() + "s"
	if sentence == 5:
		sent = "whenever i " + getVerb() + ", i " + getVerb()
	if sentence == 6:
		sent = "im being " + getAdj() + " in my " + getNoun()
	if sentence == 7: 
		sent = "bae: " + getAdj() + " " + getNoun() + "<br> me: " + getNoun()
	if sentence == 8: 
		sent = "for every " + getAdj() + " " + getNoun() + " theres a " + getNoun() + " for me"
	if sentence == 9:
		sent = "i dont need a " + getNoun() + " when i have the " + getNoun() 
	if sentence == 10:
		sent = "imagine what would happen if we combined " + getNoun() + " and " + getNoun()
	if sentence == 11:
		sent = "the world has come to a "+ getAdj() + " end. " + getNoun()+ " have taken over. All hope is lost"
	if sentence == 12:
		sent = "why cant we all have " + getAdj() + " " + getNoun()
	if sentence == 13:
		sent = "do you ever think about how " + getNoun() + " and " + getNoun() + " are really similar"
	if sentence == 14:
		sent = "todo list <br>1. " + getVerb() + " <br> 2. " + getVerb() + "<br> 3. " + getVerb()
	if sentence == 15:
		sent = "my friends describe me as " + getAdj()
	return sent

def Post(post):
	print client.create_text("robotposting",body=post)

# Make the request
formattedJson = json.dumps(client.info(), sort_keys=True, indent=4, separators=(',', ': '))

parsed = json.loads(formattedJson)

flag = 0
while(flag == 0):
	flag1 = 0
	req = input("Generate Post (1) or Quit (2)")
	if req == 2:
		flag = 1
	if req == 1:
		while (flag1 == 0):
			post = getPost()
			print post
			req = input("Post (1) or Regenerate (other)")
			if req == 1:
				Post(post)
				flag1 = 1


