# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('room_per1', models.CharField(max_length=3)),
                ('room_per2', models.CharField(max_length=3)),
                ('room_per3', models.CharField(max_length=3)),
                ('room_per4', models.CharField(max_length=3)),
                ('room_per5', models.CharField(max_length=3)),
                ('room_per6', models.CharField(max_length=3)),
                ('room_per7', models.CharField(max_length=3)),
                ('room_per8', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('6', '6th Grader'), ('7', '7th Grader'), ('8', '8th Grader'), ('9', '9th Grader'), ('10', '10th Grader'), ('11', '11th Grader'), ('12', '12th Grader')], default='6', max_length=2)),
                ('class_per1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 1+', to='tracker.Class')),
                ('class_per2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 2+', to='tracker.Class')),
                ('class_per3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 3+', to='tracker.Class')),
                ('class_per4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 4+', to='tracker.Class')),
                ('class_per5', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 5+', to='tracker.Class')),
                ('class_per6', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 6+', to='tracker.Class')),
                ('class_per7', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 7+', to='tracker.Class')),
                ('class_per8', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 8+', to='tracker.Class')),
            ],
        ),
    ]
