# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160218_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='room_per1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room_per8',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
