# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160218_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_per1',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 1443+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per2',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 2+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per3',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 3+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per4',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 4+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per5',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 5+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per6',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 6+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per7',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 7+', to='tracker.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_per8',
            field=models.ForeignKey(default=1443, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Period 8+', to='tracker.Class'),
        ),
    ]
